"""
arXiv 論文篩選系統設定檔
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# 載入環境變數
load_dotenv()

# =============================================================================
# 輸出設定 (從環境變數載入)
# =============================================================================
OUTPUT_DIR = os.path.expanduser(os.getenv("OUTPUT_DIR", "~/arxiv-papers"))
TOP_N = int(os.getenv("TOP_N", "10"))  # 篩選前 N 篇論文

# =============================================================================
# arXiv API 設定
# =============================================================================
ARXIV_REQUEST_DELAY = 1.5  # 每次請求間隔秒數
ARXIV_MAX_RESULTS = 2000  # 單分類最大結果數

# 要查詢的 AI 相關類別
ARXIV_CATEGORIES = [
    "cs.AI",   # Artificial Intelligence
    "cs.LG",   # Machine Learning
    "cs.CL",   # Computation and Language (NLP)
    "cs.CV",   # Computer Vision
    "cs.NE",   # Neural and Evolutionary Computing
   #  "stat.ML", # Machine Learning (Statistics)
]

# =============================================================================
# LLM 設定 (從環境變數載入)
# =============================================================================
LLM_MODEL = os.getenv("LLM_MODEL", "gemini-2.5-flash")
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.1"))

# Thinking 設定 (僅 Gemini 2.5 系列支援)
# 設為 0 或不設定 = 關閉 thinking
# 設為 1-24576 = 開啟 thinking 並設定 token 預算
LLM_THINKING_BUDGET = int(os.getenv("LLM_THINKING_BUDGET", "0"))

# =============================================================================
# 評估標準 Prompt
# =============================================================================
EVALUATION_PROMPT1 = """你是 AI 應用工程專家，專注於 LLM 系統落地、部署與**技術選型**。
從以下論文列表中，選出最具價值的 {top_n} 篇論文。

## 評估標準 (依優先級排序)

1. **系統架構與設計**
   - RAG (檢索策略/分塊優化)
   - Agent (規劃/工具使用/多Agent協作)
   - Context Engineering、Prompt Optimization

2. **關鍵技術綜述 (Survey) 與大廠報告**  <-- (將 Survey 提升至高優先級)
   - **能幫助工程師釐清技術路線、節省調研時間的高品質 Survey**
   - **針對新興熱門領域 (如 Agentic Workflow, Reasoning) 的系統性整理**
   - 大廠評估報告 (Capabilities, Safety, False Refusal)

3. **流程與評估優化**
   - LLMOps、Auto-Evaluation (LLM-as-a-Judge, **Agent-as-a-Judge**)
   - Data Flywheel、Error Analysis

4. **推論效率與成本**
   - Latency 優化、Throughput 提升
   - Quantization (量化)、FlashAttention、VRAM 優化

5. **落地可行性**
   - 真實場景 (Real-world) 驗證
   - 魯棒性 (Robustness)

## 排除條件 (請跳過這類論文)

- 純數學理論推導
- 全新的基礎模型訓練架構設計 (除非涉及推論加速)
- 僅適用於學術刷榜但無實際應用價值的微小精度提升
- 純 CV/NLP 基礎任務改進 (除非與 LLM 應用相關)
- **(注意：請勿排除具有高度工程參考價值的 Survey/Review 論文)**

## 論文列表

{papers_list}

## 回傳格式

僅回傳 JSON，不要有其他文字或 markdown 格式標記:
{{"rank": [索引號陣列]}}

範例:
{{"rank": [5, 12, 3]}}

注意:
- **結果中必須包含至少 1-2 篇高品質的領域綜述 (Survey)，若列表包含此類論文。**
- rank 陣列長度必須是 {top_n}
- 索引號從 0 開始"""


EVALUATION_PROMPT2 = """你是 AI 應用工程專家，專注於 LLM 系統落地、部署與**技術選型**。
從以下論文列表中，選出最具價值的 {top_n} 篇論文。

## 評估標準 (依優先級排序)

1. **系統架構與設計**
   - RAG (檢索策略/分塊優化)
   - Agent (規劃/工具使用/多Agent協作)
   - Context Engineering、Prompt Optimization

2. **關鍵技術綜述 (Survey) 與大廠報告**  <-- (將 Survey 提升至高優先級)
   - **能幫助工程師釐清技術路線、節省調研時間的高品質 Survey**
   - **針對新興熱門領域 (如 Agentic Workflow, Reasoning) 的系統性整理**
   - 大廠評估報告 (Capabilities, Safety, False Refusal)

3. **流程與評估優化**
   - LLMOps、Auto-Evaluation (LLM-as-a-Judge, **Agent-as-a-Judge**)
   - Data Flywheel、Error Analysis

4. **推論效率與成本**
   - Latency 優化、Throughput 提升
   - Quantization (量化)、FlashAttention、VRAM 優化

5. **落地可行性**
   - 真實場景 (Real-world) 驗證
   - 魯棒性 (Robustness)

## 排除條件 (請跳過這類論文)

- 純數學理論推導
- 全新的基礎模型訓練架構設計 (除非涉及推論加速)
- 僅適用於學術刷榜但無實際應用價值的微小精度提升
- 純 CV/NLP 基礎任務改進 (除非與 LLM 應用相關)
- **(注意：請勿排除具有高度工程參考價值的 Survey/Review 論文)**

## 論文列表

{papers_list}

## 回傳格式

僅回傳 JSON，不要有其他文字或 markdown 格式標記:
{{"rank": [索引號陣列], "reasons": ["每篇的一句話原因"]}}

範例:
{{"rank": [5, 12, 3], "reasons": ["RAG分塊策略創新", "Agent評估技術綜述", "量化部署方案"]}}

注意:
- **結果中必須包含至少 1-2 篇高品質的領域綜述 (Survey)，若列表包含此類論文。**
- rank 陣列長度必須是 {top_n}
- reasons 陣列長度必須與 rank 相同
- 索引號從 0 開始
- 原因請用繁體中文，每個原因控制在 15 字以內"""

# =============================================================================
# 輸出 Markdown 模板
# =============================================================================
MARKDOWN_TEMPLATE = """# arXiv AI 論文精選 - {date}

> 自動篩選自 arXiv，共掃描 {total_count} 篇，精選 Top {top_n}

## 排名

| # | 標題 | 類別 | 原因 |
|---|------|------|------|
{ranking_table}

---

## 論文詳情

{paper_details}

---

*Generated by arxiv-selector | Model: {model}*
"""

PAPER_DETAIL_TEMPLATE = """### {rank}. {title}

- **arXiv**: [{arxiv_id}]({url})
- **類別**: {categories}
- **作者**: {authors}
- **入選原因**: {reason}

<details>
<summary>摘要 (點擊展開)</summary>

{abstract}

</details>

"""
